
import type { Metadata } from "next";
import "./globals.css";
import Provider from "./component/provider";
import { Eater, Creepster, Nosifer, Roboto } from "next/font/google";
import Themetry from "./component/Themetry"
 const metadata: Metadata = {
  title: "Blog",
  description: "Generated by create next app",
};

export const eater = Eater({
  weight: "400",
  subsets: ["latin"],
});

export const roboto = Roboto({
  weight: "400",
  subsets: ["latin"],
});

export const creepster = Creepster({
  weight: "400",
  subsets: ["latin"],
});

export const nosifer = Nosifer({
  weight: "400",
  subsets: ["latin"],
});

export default function RootLayout({
  children,

}: Readonly<{
  children: React.ReactNode;

}>) {
  return (
    <html lang="en">
      <body className={roboto.className} style={{ height: "100%",minHeight: "100vh", margin: 0, padding: 0, overflow: "hidden" }}>
        <Themetry>
          <Provider>
            {/* <div className="flex"> */}
              {/* <aside className="w-64 bg-gray-200 p-4">{home}</aside> */}

              {children}

              {/* <aside className="w-64 bg-gray-100 p-4">{analytic}</aside> */}
            {/* </div> */}
          </Provider>
        </Themetry>
      </body>
    </html>
  );
}
