// app/layout.tsx
import type { Metadata } from "next";
import * as React from "react";
import Grid from "@mui/material/Grid";
import Box from "@mui/material/Box";

export const metadata: Metadata = {
  title: "Profile Page",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
      // <Box
      //   sx={{
      //     minHeight: "100vh",
      //     margin: 0,
      //     padding: 0,
      //   }}
      // >
        <Box
          sx={{ flexGrow: 1, minHeight: "100vh", backgroundColor: "#1B3F3C" }}
        >
          <Grid container>
            <Grid
              size={3}
              sx={{
                borderRight: "0.5px solid rgb(232, 232, 232)",
                minHeight: "100vh",
              }}
            >
              Feature
            </Grid>
            <Grid
              size={6}
              sx={{
                borderRight: "0.5px solid rgb(232, 232, 232)",
              }}
            >
              {children}
            </Grid>
            <Grid size="auto">Side</Grid>
          </Grid>
        </Box>
      // </Box>
  );
}
