import { Box } from "@mui/material";
import type { Metadata } from "next";
export const metadata: Metadata = {
  title: "Login page",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <Box sx={{
        minHeight: "100vh",
        // backgroundImage: "url('/halloweenHd.jpg')",
        // backgroundSize: "cover",
        // backgroundPosition: "center",
        display: "flex",
        justifyContent: "center",
        alignItems: "center",
      }}>
        {children}
    </Box>
  );
}
